version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.8.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: ls -al
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules

  test:
    docker:
      - image: circleci/node:8.8.1
      - image: trufflesuite/ganache-cli:v6.0.3
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: npm test

  deploy-to-canary:
    docker:
      - image: circleci/node:8.8.1
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          key: deploy-to-canary
      - run: "[ -d ~/repo/canary-build ] && mv ~/repo/canary-build ~/repo/build || echo 'No existing build dir'"
      - run: "[ -f ~/repo/build/contracts/MoneyMarket.json ] && rm ~/repo/build/contracts/MoneyMarket.json"
      - run: "[ -f ~/repo/build/contracts/InterestRateStorage.json ] && rm ~/repo/build/contracts/InterestRateStorage.json"
      - run: RINKEBY_PRIVATE_KEY="$CANARY_PRIVATE_KEY" ./node_modules/truffle/build/cli.bundled.js deploy --network rinkeby
      - run: RINKEBY_PRIVATE_KEY="$CANARY_PRIVATE_KEY" ./node_modules/truffle/build/cli.bundled.js exec --network rinkeby ./addresses.js 1> /dev/null 2> canary-addresses.json
      - run: mv ~/repo/build ~/repo/canary-build
      - save_cache:
          key: deploy-to-canary-{{ epoch }}
          paths:
            - ~/repo/canary-build
          when: on_success
      - persist_to_workspace:
          root: ~/repo
          paths:
            - canary-build
      - store_artifacts:
          path: canary-addresses.json
          destination: canary/addresses.json
      - store_artifacts:
          path: canary-build
          destination: canary-build

  deploy-to-alpha:
    docker:
      - image: circleci/node:8.8.1
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          key: deploy-to-alpha
      - run: "[ -d ~/repo/alpha-build ] && mv ~/repo/alpha-build ~/repo/build || echo 'No existing build dir'"
      - run: "[ -f ~/repo/build/contracts/MoneyMarket.json ] && rm ~/repo/build/contracts/MoneyMarket.json"
      - run: "[ -f ~/repo/build/contracts/InterestRateStorage.json ] && rm ~/repo/build/contracts/InterestRateStorage.json"
      - run: RINKEBY_PRIVATE_KEY="$ALPHA_PRIVATE_KEY" ./node_modules/truffle/build/cli.bundled.js deploy --network rinkeby
      - run: RINKEBY_PRIVATE_KEY="$ALPHA_PRIVATE_KEY" ./node_modules/truffle/build/cli.bundled.js exec --network rinkeby ./addresses.js 1> /dev/null 2> alpha-addresses.json
      - run: mv ~/repo/build ~/repo/alpha-build
      - save_cache:
          key: deploy-to-alpha-{{ epoch }}
          paths:
            - ~/repo/alpha-build
          when: on_success
      - persist_to_workspace:
          root: ~/repo
          paths:
            - alpha-build
      - store_artifacts:
          path: alpha-addresses.json
          destination: alpha/addresses.json
      - store_artifacts:
          path: alpha-build
          destination: alpha-build

  rotate-canary:
    docker:
      - image: circleci/node:8.8.1
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: mv ~/repo/canary-build ~/repo/build
      - run: RINKEBY_PRIVATE_KEY="$CANARY_PRIVATE_KEY" ./node_modules/truffle/build/cli.bundled.js exec --network rinkeby ./allow.js

  rotate-alpha:
    docker:
      - image: circleci/node:8.8.1
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: mv ~/repo/alpha-build ~/repo/build
      - run: RINKEBY_PRIVATE_KEY="$ALPHA_PRIVATE_KEY" ./node_modules/truffle/build/cli.bundled.js exec --network rinkeby ./allow.js

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-to-canary:
          requires:
            - test
          filters:
            branches:
              only: /(^master$)|(.*deploy$)/
      - deploy-to-alpha:
          requires:
            - test
          filters:
            branches:
              only: /(^master$)|(.*deploy$)/
      - hold-canary:
          type: approval
          requires:
            - deploy-to-canary
      - rotate-canary:
          requires:
            - hold-canary
      - hold-alpha:
          type: approval
          requires:
            - deploy-to-alpha
      - rotate-alpha:
          requires:
            - hold-alpha
